services:

  postgres:
    image: postgres:17
    container_name: cyberwatch-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - cyberwatch_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./cyberwatch-backend
      dockerfile: Dockerfile

    container_name: cyberwatch-backend
    restart: unless-stopped

    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./cyberwatch-frontend
      dockerfile: Dockerfile

    container_name: cyberwatch-frontend
    restart: unless-stopped

    ports:
      - "4200:80"

    depends_on:
      - backend

volumes:
  cyberwatch_postgres_data: